// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0NOja3o5tyFBkdJqlZxyPfK03yJCZy8A',
    appId: '1:786124177724:web:f9ebfde16b6cb4501e9e39',
    messagingSenderId: '786124177724',
    projectId: 'flutter-chat-app-8890b',
    authDomain: 'flutter-chat-app-8890b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8890b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2-PZJTOXFpgEDGG-wrsb9yRM6Tdce5k0',
    appId: '1:786124177724:android:559862785ce8a4701e9e39',
    messagingSenderId: '786124177724',
    projectId: 'flutter-chat-app-8890b',
    storageBucket: 'flutter-chat-app-8890b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh9sR_D7d96iwBx8mSrAPo3rmRZT98x64',
    appId: '1:786124177724:ios:b92eb3c3bebe89251e9e39',
    messagingSenderId: '786124177724',
    projectId: 'flutter-chat-app-8890b',
    storageBucket: 'flutter-chat-app-8890b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh9sR_D7d96iwBx8mSrAPo3rmRZT98x64',
    appId: '1:786124177724:ios:b92eb3c3bebe89251e9e39',
    messagingSenderId: '786124177724',
    projectId: 'flutter-chat-app-8890b',
    storageBucket: 'flutter-chat-app-8890b.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0NOja3o5tyFBkdJqlZxyPfK03yJCZy8A',
    appId: '1:786124177724:web:ff4cf1079662e4221e9e39',
    messagingSenderId: '786124177724',
    projectId: 'flutter-chat-app-8890b',
    authDomain: 'flutter-chat-app-8890b.firebaseapp.com',
    storageBucket: 'flutter-chat-app-8890b.firebasestorage.app',
  );

}